package com.paintcolor.drawing.paint.firebase.event

object EventName {
    const val splash_open = "splash_open"
    const val language_fo_open = "language_fo_open"
    const val language_user_view = "language_user_view"
    const val language_fo_save_click = "language_fo_save_click"
    const val language_fo_choose = "language_fo_choose"
    const val onboarding_1_view = "onboarding1_view"
    const val onboarding_next_click = "onboarding_next_click"
    const val onboard_open = "onboard_open"
    const val permission_open = "permission_open"
    const val permission_allow_click = "permission_allow_click"
    const val permission_continue_click = "permission_continue_click"

    const val interest_view = "interest_view"
    const val interest_next_click = "interest_next_click"
    const val color_palette_view = "color_palette_view"
    const val color_palette_color_click = "color_palette_color_click"
    const val rate_show = "rate_show"
    const val rate_not_now = "rate_not_now"
    const val rate_submit = "rate_submit"
    const val home_open = "home_open"
    const val home_view = "home_view"
    const val home_see_all_click = "home_see_all_click"
    const val category_item_choose = "category_item_choose"
    const val home_create_click = "home_create_click"
    const val sketch_tutorial_view = "sketch_tutorial_view"
    const val sketch_continue_click = "sketch_continue_click"
    const val sketch_draw_view = "sketch_draw_view"
    const val sketch_draw_flip_click = "sketch_draw_flip_click"
    const val sketch_draw_lock_click = "sketch_draw_lock_click"
    const val sketch_draw_record_click = "sketch_draw_record_click"
    const val sketch_draw_opacity_click = "sketch_draw_opacity_click"
    const val sketch_draw_flash_click = "sketch_draw_flash_click"
    const val edit_paint_view = "edit_paint_view"
    const val edit_paint_pen_click = "edit_paint_pen_click"
    const val edit_paint_color_click = "edit_paint_color_click"
    const val edit_paint_undo_click = "edit_paint_undo_click"
    const val edit_paint_redo_click = "edit_paint_redo_click"
    const val edit_paint_clear_click = "edit_paint_clear_click"
    const val edit_paint_morepaint_click = "edit_paint_morepaint_click"
    const val paint_brush_view = "paint_brush_view"
    const val edit_paint_save_click = "edit_paint_save_click"
    const val edit_paint_import_image_click = "edit_paint_import_image_click"
    const val color_palettes_view = "color_palettes_view"
    const val colorpalette_custom_add_click = "colorpalette_custom_add_click"
    const val color_palette_edit_click = "color_palette_edit_click"
    const val custom_palettes_view = "custom_palettes_view"
    const val custom_palettes_save_click = "custom_palettes_save_click"
    const val success_view = "success_view"
    const val explore_more_click = "explore_more_click"
    const val success_download_click = "success_download_click"
    const val success_share_click = "success_share_click"
    const val success_home_click = "success_home_click"
    const val my_creation_coloring_view = "my_creation_coloring_view"
    const val my_creation_drawing_view = "my_creation_drawing_view"
    const val my_creation_explore_click = "my_creation_explore_click"
    const val paint_result_view = "paint_result_view"
    const val paint_result_edit_click = "paint_result_edit_click"
    const val paint_result_share_click = "paint_result_share_click"
    const val paint_result_download_click = "paint_result_download_click"
    const val paint_result_delete_click = "paint_result_delete_click"

    const val setting_view = "setting_view"
    const val setting_lang_click = "setting_lang_click"
    const val setting_share_click = "setting_share_click"
    const val setting_policy_click = "setting_policy_click"
    const val uninstall_click = "uninstall_click"
    const val uninstall_explore_click = "uninstall_explore_click"
    const val uninstall_try_again_click = "uninstall_try_again_click"
    const val dontuninstall_click = "dontuninstall_click"
    const val still_want_uninstall_click = "still_want_uninstall_click"
    const val reason_uninstall = "reason_uninstall"
    const val uninstall_canel_click = "uninstall_canel_click"



}